<?php

namespace ContainerZKOihSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S4o4C8_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.s4o4C8.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s4o4C8.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contact' => ['privates', '.errored..service_locator.s4o4C8..App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.s4o4C8.": it needs an instance of "App\\Entity\\Contact" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'contact' => 'App\\Entity\\Contact',
            'entityManager' => '?',
        ]);
    }
}
