<?php

namespace ContainerZKOihSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorie2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ZGOqsj7.App\Entity\Categorie' shared service.
     *
     * @return \App\Entity\Categorie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZGOqsj7": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".');
    }
}
