<?php

namespace ContainerZKOihSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZGOqsj7.App\Controller\CategorieController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ZGOqsj7'] ?? $container->load('get_ServiceLocator_ZGOqsj7Service'));

        if (isset($container->privates['.service_locator.ZGOqsj7.App\\Controller\\CategorieController::edit()'])) {
            return $container->privates['.service_locator.ZGOqsj7.App\\Controller\\CategorieController::edit()'];
        }

        return $container->privates['.service_locator.ZGOqsj7.App\\Controller\\CategorieController::edit()'] = $a->withContext('App\\Controller\\CategorieController::edit()', $container);
    }
}
