<?php

namespace ContainerZKOihSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.s4o4C8..App\Controller\ContactController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.s4o4C8.'] ?? $container->load('get_ServiceLocator_S4o4C8_Service'));

        if (isset($container->privates['.service_locator.s4o4C8..App\\Controller\\ContactController::edit()'])) {
            return $container->privates['.service_locator.s4o4C8..App\\Controller\\ContactController::edit()'];
        }

        return $container->privates['.service_locator.s4o4C8..App\\Controller\\ContactController::edit()'] = $a->withContext('App\\Controller\\ContactController::edit()', $container);
    }
}
