<?php

namespace ContainerZKOihSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.MHM6yj9.App\Controller\ContactController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MHM6yj9.App\\Controller\\ContactController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contact' => ['privates', '.errored..service_locator.MHM6yj9.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.MHM6yj9": it needs an instance of "App\\Entity\\Contact" but this type has been excluded in "config/services.yaml".'],
        ], [
            'contact' => 'App\\Entity\\Contact',
        ]))->withContext('App\\Controller\\ContactController::show()', $container);
    }
}
