<?php

namespace ContainerZKOihSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\UtilisateurAuthenticator' shared autowired service.
     *
     * @return \App\Security\UtilisateurAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\UtilisateurAuthenticator'] = new \App\Security\UtilisateurAuthenticator(($container->services['router'] ?? self::getRouterService($container)));
    }
}
