<?php

namespace ContainerZKOihSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\UtilisateurController' shared autowired service.
     *
     * @return \App\Controller\UtilisateurController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\UtilisateurController'] = $instance = new \App\Controller\UtilisateurController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\UtilisateurController', $container));

        return $instance;
    }
}
