<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \App\Entity\Contact implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Date' => [parent::class, 'Date', null],
        "\0".parent::class."\0".'Email' => [parent::class, 'Email', null],
        "\0".parent::class."\0".'Message' => [parent::class, 'Message', null],
        "\0".parent::class."\0".'Nom' => [parent::class, 'Nom', null],
        "\0".parent::class."\0".'Objet' => [parent::class, 'Objet', null],
        "\0".parent::class."\0".'Prenom' => [parent::class, 'Prenom', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        'Date' => [parent::class, 'Date', null],
        'Email' => [parent::class, 'Email', null],
        'Message' => [parent::class, 'Message', null],
        'Nom' => [parent::class, 'Nom', null],
        'Objet' => [parent::class, 'Objet', null],
        'Prenom' => [parent::class, 'Prenom', null],
        'id' => [parent::class, 'id', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
