<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Article implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Categorie' => [parent::class, 'Categorie', null],
        "\0".parent::class."\0".'Contenu' => [parent::class, 'Contenu', null],
        "\0".parent::class."\0".'Date' => [parent::class, 'Date', null],
        "\0".parent::class."\0".'Resume' => [parent::class, 'Resume', null],
        "\0".parent::class."\0".'Titre' => [parent::class, 'Titre', null],
        "\0".parent::class."\0".'Validation' => [parent::class, 'Validation', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        'Categorie' => [parent::class, 'Categorie', null],
        'Contenu' => [parent::class, 'Contenu', null],
        'Date' => [parent::class, 'Date', null],
        'Resume' => [parent::class, 'Resume', null],
        'Titre' => [parent::class, 'Titre', null],
        'Validation' => [parent::class, 'Validation', null],
        'id' => [parent::class, 'id', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
