<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Article__CLASSMETADATA__' => 0,
'App__Entity__Categorie__CLASSMETADATA__' => 1,
'App__Entity__Contact__CLASSMETADATA__' => 2,
'App__Entity__Evenement__CLASSMETADATA__' => 3,
'App__Entity__Utilisateur__CLASSMETADATA__' => 4,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Article',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ArticleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Titre' => $o[2],
                        'Date' => $o[3],
                        'Resume' => $o[4],
                        'Contenu' => $o[5],
                        'Validation' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'titre' => 'Titre',
                        'date' => 'Date',
                        'resume' => 'Resume',
                        'contenu' => 'Contenu',
                        'validation' => 'Validation',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Titre' => 'titre',
                        'Date' => 'date',
                        'Resume' => 'resume',
                        'Contenu' => 'contenu',
                        'Validation' => 'validation',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'article',
                    ],
                ],
                'associationMappings' => [
                    [
                        'utilisateur' => $o[7],
                        'Categorie' => $o[9],
                    ],
                ],
                'idGenerator' => [
                    $o[11],
                ],
                'name' => [
                    'App\\Entity\\Article',
                    8 => 'utilisateur_id',
                    10 => 'categorie_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'datetime',
                    'string',
                    'string',
                    'boolean',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Titre',
                    'Date',
                    'Resume',
                    'Contenu',
                    'Validation',
                ],
                'columnName' => [
                    1 => 'id',
                    'titre',
                    'date',
                    'resume',
                    'contenu',
                    'validation',
                ],
                'length' => [
                    2 => 50,
                    4 => 300,
                    2000,
                ],
                'fetch' => [
                    7 => 2,
                    9 => 2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\Article',
                    9 => 'App\\Entity\\Article',
                ],
                'inversedBy' => [
                    7 => 'Article',
                    9 => 'articles',
                ],
                'sourceToTargetKeyColumns' => [
                    7 => [
                        'utilisateur_id' => 'id',
                    ],
                    9 => [
                        'categorie_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    7 => [
                        'id' => 'utilisateur_id',
                    ],
                    9 => [
                        'id' => 'categorie_id',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                    9 => [
                        $o[10],
                    ],
                ],
                'joinColumnFieldNames' => [
                    7 => [
                        'utilisateur_id' => 'utilisateur_id',
                    ],
                    9 => [
                        'categorie_id' => 'categorie_id',
                    ],
                ],
                'unique' => [
                    8 => false,
                    10 => false,
                ],
                'nullable' => [
                    8 => false,
                    10 => false,
                ],
                'referencedColumnName' => [
                    8 => 'id',
                    10 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'utilisateur',
                    9 => 'Categorie',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\Utilisateur',
                    9 => 'App\\Entity\\Categorie',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Categorie',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CategorieRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nom' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'Nom',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nom' => 'nom',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'categorie',
                    ],
                ],
                'associationMappings' => [
                    [
                        'articles' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\Categorie',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nom',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                ],
                'length' => [
                    2 => 50,
                ],
                'cascade' => [
                    3 => [
                        'remove',
                    ],
                ],
                'fetch' => [
                    3 => 2,
                ],
                'orphanRemoval' => [
                    3 => true,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\Categorie',
                ],
                'mappedBy' => [
                    3 => 'Categorie',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'articles',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\Article',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Contact',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ContactRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Email' => $o[2],
                        'Objet' => $o[3],
                        'Message' => $o[4],
                        'Nom' => $o[5],
                        'Prenom' => $o[6],
                        'Date' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'Email',
                        'objet' => 'Objet',
                        'message' => 'Message',
                        'nom' => 'Nom',
                        'prenom' => 'Prenom',
                        'date' => 'Date',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Email' => 'email',
                        'Objet' => 'objet',
                        'Message' => 'message',
                        'Nom' => 'nom',
                        'Prenom' => 'prenom',
                        'Date' => 'date',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'contact',
                    ],
                ],
                'associationMappings' => [
                    [
                        'utilisateur' => $o[8],
                    ],
                ],
                'idGenerator' => [
                    $o[10],
                ],
                'name' => [
                    'App\\Entity\\Contact',
                    9 => 'utilisateur_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'text',
                    'string',
                    'string',
                    'datetime',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Email',
                    'Objet',
                    'Message',
                    'Nom',
                    'Prenom',
                    'Date',
                ],
                'columnName' => [
                    1 => 'id',
                    'email',
                    'objet',
                    'message',
                    'nom',
                    'prenom',
                    'date',
                ],
                'length' => [
                    2 => 255,
                    255,
                    5 => 50,
                    50,
                ],
                'fetch' => [
                    8 => 2,
                ],
                'sourceEntity' => [
                    8 => 'App\\Entity\\Contact',
                ],
                'inversedBy' => [
                    8 => 'Contact',
                ],
                'sourceToTargetKeyColumns' => [
                    8 => [
                        'utilisateur_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    8 => [
                        'id' => 'utilisateur_id',
                    ],
                ],
                'joinColumns' => [
                    8 => [
                        $o[9],
                    ],
                ],
                'joinColumnFieldNames' => [
                    8 => [
                        'utilisateur_id' => 'utilisateur_id',
                    ],
                ],
                'referencedColumnName' => [
                    9 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    8 => 'utilisateur',
                ],
                'targetEntity' => [
                    8 => 'App\\Entity\\Utilisateur',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Evenement',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\EvenementRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Titre' => $o[2],
                        'Date' => $o[3],
                        'Resume' => $o[4],
                        'Contenu' => $o[5],
                        'Validation' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'titre' => 'Titre',
                        'date' => 'Date',
                        'resume' => 'Resume',
                        'contenu' => 'Contenu',
                        'validation' => 'Validation',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Titre' => 'titre',
                        'Date' => 'date',
                        'Resume' => 'resume',
                        'Contenu' => 'contenu',
                        'Validation' => 'validation',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'evenement',
                    ],
                ],
                'associationMappings' => [
                    [
                        'utilisateurs' => $o[7],
                        'utilisateurOrganisation' => $o[8],
                    ],
                ],
                'idGenerator' => [
                    $o[10],
                ],
                'name' => [
                    'App\\Entity\\Evenement',
                    9 => 'utilisateur_organisation_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'datetime',
                    'string',
                    'string',
                    'boolean',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Titre',
                    'Date',
                    'Resume',
                    'Contenu',
                    'Validation',
                ],
                'columnName' => [
                    1 => 'id',
                    'titre',
                    'date',
                    'resume',
                    'contenu',
                    'validation',
                ],
                'length' => [
                    2 => 255,
                    4 => 300,
                    2000,
                ],
                'fetch' => [
                    7 => 2,
                    2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\Evenement',
                    'App\\Entity\\Evenement',
                ],
                'mappedBy' => [
                    7 => 'Evenement',
                ],
                'inversedBy' => [
                    8 => 'EvenementsOrganisation',
                ],
                'sourceToTargetKeyColumns' => [
                    8 => [
                        'utilisateur_organisation_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    8 => [
                        'id' => 'utilisateur_organisation_id',
                    ],
                ],
                'joinColumns' => [
                    8 => [
                        $o[9],
                    ],
                ],
                'joinColumnFieldNames' => [
                    8 => [
                        'utilisateur_organisation_id' => 'utilisateur_organisation_id',
                    ],
                ],
                'unique' => [
                    9 => false,
                ],
                'nullable' => [
                    9 => false,
                ],
                'referencedColumnName' => [
                    9 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'utilisateurs',
                    'utilisateurOrganisation',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\Utilisateur',
                    'App\\Entity\\Utilisateur',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Utilisateur',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UtilisateurRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'nom' => $o[2],
                        'prenom' => $o[3],
                        'email' => $o[4],
                        'roles' => $o[5],
                        'password' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'utilisateur',
                        'uniqueConstraints' => [
                            'UNIQ_IDENTIFIER_EMAIL' => [
                                'fields' => [
                                    'email',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'Evenement' => $o[7],
                        'EvenementsOrganisation' => $o[11],
                        'Contact' => $o[12],
                        'Article' => $o[13],
                    ],
                ],
                'idGenerator' => [
                    $o[14],
                ],
                'name' => [
                    'App\\Entity\\Utilisateur',
                    8 => 'utilisateur_evenement',
                    'utilisateur_id',
                    'evenement_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'json',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'nom',
                    'prenom',
                    'email',
                    'roles',
                    'password',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                    'prenom',
                    'email',
                    'roles',
                    'password',
                ],
                'length' => [
                    2 => 50,
                    50,
                    180,
                ],
                'fetch' => [
                    7 => 2,
                    11 => 2,
                    2,
                    2,
                ],
                'isOnDeleteCascade' => [
                    7 => true,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\Utilisateur',
                    11 => 'App\\Entity\\Utilisateur',
                    'App\\Entity\\Utilisateur',
                    'App\\Entity\\Utilisateur',
                ],
                'inversedBy' => [
                    7 => 'utilisateurs',
                ],
                'joinTable' => [
                    7 => $o[8],
                ],
                'joinTableColumns' => [
                    7 => [
                        'utilisateur_id',
                        'evenement_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    7 => [
                        'utilisateur_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    7 => [
                        'evenement_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    8 => [
                        $o[9],
                    ],
                ],
                'inverseJoinColumns' => [
                    8 => [
                        $o[10],
                    ],
                ],
                'onDelete' => [
                    9 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    9 => 'id',
                    'id',
                ],
                'mappedBy' => [
                    11 => 'utilisateurOrganisation',
                    'utilisateur',
                    'utilisateur',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'Evenement',
                    11 => 'EvenementsOrganisation',
                    'Contact',
                    'Article',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\Evenement',
                    11 => 'App\\Entity\\Evenement',
                    'App\\Entity\\Contact',
                    'App\\Entity\\Article',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
