<?php

namespace ContainerHPJxHrb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MHM6yj9.App\Entity\Contact' shared service.
     *
     * @return \App\Entity\Contact
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MHM6yj9": it needs an instance of "App\\Entity\\Contact" but this type has been excluded in "config/services.yaml".');
    }
}
