<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHPJxHrb\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHPJxHrb/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerHPJxHrb.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerHPJxHrb\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerHPJxHrb\App_KernelProdDebugContainer([
    'container.build_hash' => 'HPJxHrb',
    'container.build_id' => '7f981cc8',
    'container.build_time' => 1728169072,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHPJxHrb');
